name: CI

on:
  push:
    branches:
      - main         # Trigger on pushes to the `main` branch
      - 'feature/*'  # Trigger on pushes to any branch matching the `feature/` pattern
  pull_request:       # Trigger on pull requests targeting the `main` branch

jobs:
  test:
    # Explicitly specify the runner version
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
          JWT_SECRET: your_jwt_secret
        run: npm test
        working-directory: backend
