name: CI

on:
  push:
    branches:
      - main         # Trigger on pushes to the `main` branch
      - 'feature/*'  # Trigger on pushes to any branch matching the `feature/` pattern
  pull_request:       # Trigger on pull requests targeting the `main` branch

jobs:
  test:
    # Explicitly specify the runner version
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0' # Use a compatible version of Node.js

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        working-directory: backend

      - name: Run critical tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test -- --testPathPattern=tests/tasks.test.js
        working-directory: backend
